// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/digitalocean/godo (interfaces: BatchInferenceService)
//
// Generated by this command:
//
//	mockgen -destination=./mocks.go -package genaibatchinference github.com/digitalocean/godo BatchInferenceService
//

// Package genaibatchinference is a generated GoMock package.
package genaibatchinference

import (
	context "context"
	io "io"
	reflect "reflect"

	godo "github.com/digitalocean/godo"
	gomock "go.uber.org/mock/gomock"
)

// MockBatchInferenceService is a mock of BatchInferenceService interface.
type MockBatchInferenceService struct {
	ctrl     *gomock.Controller
	recorder *MockBatchInferenceServiceMockRecorder
	isgomock struct{}
}

// MockBatchInferenceServiceMockRecorder is the mock recorder for MockBatchInferenceService.
type MockBatchInferenceServiceMockRecorder struct {
	mock *MockBatchInferenceService
}

// NewMockBatchInferenceService creates a new mock instance.
func NewMockBatchInferenceService(ctrl *gomock.Controller) *MockBatchInferenceService {
	mock := &MockBatchInferenceService{ctrl: ctrl}
	mock.recorder = &MockBatchInferenceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatchInferenceService) EXPECT() *MockBatchInferenceServiceMockRecorder {
	return m.recorder
}

// CancelJob mocks base method.
func (m *MockBatchInferenceService) CancelJob(arg0 context.Context, arg1 string) (*godo.Batch, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelJob", arg0, arg1)
	ret0, _ := ret[0].(*godo.Batch)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CancelJob indicates an expected call of CancelJob.
func (mr *MockBatchInferenceServiceMockRecorder) CancelJob(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelJob", reflect.TypeOf((*MockBatchInferenceService)(nil).CancelJob), arg0, arg1)
}

// CreateJob mocks base method.
func (m *MockBatchInferenceService) CreateJob(arg0 context.Context, arg1 *godo.CreateBatchRequest) (*godo.Batch, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJob", arg0, arg1)
	ret0, _ := ret[0].(*godo.Batch)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateJob indicates an expected call of CreateJob.
func (mr *MockBatchInferenceServiceMockRecorder) CreateJob(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJob", reflect.TypeOf((*MockBatchInferenceService)(nil).CreateJob), arg0, arg1)
}

// CreatePresignedUploadURL mocks base method.
func (m *MockBatchInferenceService) CreatePresignedUploadURL(arg0 context.Context, arg1 *godo.CreateBatchFileRequest) (*godo.CreateBatchFileResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePresignedUploadURL", arg0, arg1)
	ret0, _ := ret[0].(*godo.CreateBatchFileResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreatePresignedUploadURL indicates an expected call of CreatePresignedUploadURL.
func (mr *MockBatchInferenceServiceMockRecorder) CreatePresignedUploadURL(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePresignedUploadURL", reflect.TypeOf((*MockBatchInferenceService)(nil).CreatePresignedUploadURL), arg0, arg1)
}

// GetJob mocks base method.
func (m *MockBatchInferenceService) GetJob(arg0 context.Context, arg1 string) (*godo.Batch, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJob", arg0, arg1)
	ret0, _ := ret[0].(*godo.Batch)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetJob indicates an expected call of GetJob.
func (mr *MockBatchInferenceServiceMockRecorder) GetJob(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJob", reflect.TypeOf((*MockBatchInferenceService)(nil).GetJob), arg0, arg1)
}

// GetJobResult mocks base method.
func (m *MockBatchInferenceService) GetJobResult(arg0 context.Context, arg1 string) (*godo.BatchResultsResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobResult", arg0, arg1)
	ret0, _ := ret[0].(*godo.BatchResultsResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetJobResult indicates an expected call of GetJobResult.
func (mr *MockBatchInferenceServiceMockRecorder) GetJobResult(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobResult", reflect.TypeOf((*MockBatchInferenceService)(nil).GetJobResult), arg0, arg1)
}

// ListJobs mocks base method.
func (m *MockBatchInferenceService) ListJobs(arg0 context.Context, arg1 *godo.ListBatchesOptions) (*godo.ListBatchesResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListJobs", arg0, arg1)
	ret0, _ := ret[0].(*godo.ListBatchesResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListJobs indicates an expected call of ListJobs.
func (mr *MockBatchInferenceServiceMockRecorder) ListJobs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListJobs", reflect.TypeOf((*MockBatchInferenceService)(nil).ListJobs), arg0, arg1)
}

// UploadInputFile mocks base method.
func (m *MockBatchInferenceService) UploadInputFile(ctx context.Context, uploadURL string, content io.Reader) (*godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadInputFile", ctx, uploadURL, content)
	ret0, _ := ret[0].(*godo.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadInputFile indicates an expected call of UploadInputFile.
func (mr *MockBatchInferenceServiceMockRecorder) UploadInputFile(ctx, uploadURL, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadInputFile", reflect.TypeOf((*MockBatchInferenceService)(nil).UploadInputFile), ctx, uploadURL, content)
}
