// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/digitalocean/godo (interfaces: DedicatedInferenceService)
//
// Generated by this command:
//
//	mockgen -destination=./mocks.go -package dedicatedinference github.com/digitalocean/godo DedicatedInferenceService
//

// Package dedicatedinference is a generated GoMock package.
package dedicatedinference

import (
	context "context"
	reflect "reflect"

	godo "github.com/digitalocean/godo"
	gomock "go.uber.org/mock/gomock"
)

// MockDedicatedInferenceService is a mock of DedicatedInferenceService interface.
type MockDedicatedInferenceService struct {
	ctrl     *gomock.Controller
	recorder *MockDedicatedInferenceServiceMockRecorder
	isgomock struct{}
}

// MockDedicatedInferenceServiceMockRecorder is the mock recorder for MockDedicatedInferenceService.
type MockDedicatedInferenceServiceMockRecorder struct {
	mock *MockDedicatedInferenceService
}

// NewMockDedicatedInferenceService creates a new mock instance.
func NewMockDedicatedInferenceService(ctrl *gomock.Controller) *MockDedicatedInferenceService {
	mock := &MockDedicatedInferenceService{ctrl: ctrl}
	mock.recorder = &MockDedicatedInferenceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDedicatedInferenceService) EXPECT() *MockDedicatedInferenceServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDedicatedInferenceService) Create(arg0 context.Context, arg1 *godo.DedicatedInferenceCreateRequest) (*godo.DedicatedInference, *godo.DedicatedInferenceToken, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*godo.DedicatedInference)
	ret1, _ := ret[1].(*godo.DedicatedInferenceToken)
	ret2, _ := ret[2].(*godo.Response)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Create indicates an expected call of Create.
func (mr *MockDedicatedInferenceServiceMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDedicatedInferenceService)(nil).Create), arg0, arg1)
}

// CreateToken mocks base method.
func (m *MockDedicatedInferenceService) CreateToken(arg0 context.Context, arg1 string, arg2 *godo.DedicatedInferenceTokenCreateRequest) (*godo.DedicatedInferenceToken, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.DedicatedInferenceToken)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockDedicatedInferenceServiceMockRecorder) CreateToken(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockDedicatedInferenceService)(nil).CreateToken), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockDedicatedInferenceService) Delete(arg0 context.Context, arg1 string) (*godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*godo.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockDedicatedInferenceServiceMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDedicatedInferenceService)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockDedicatedInferenceService) Get(arg0 context.Context, arg1 string) (*godo.DedicatedInference, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*godo.DedicatedInference)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockDedicatedInferenceServiceMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDedicatedInferenceService)(nil).Get), arg0, arg1)
}

// GetGPUModelConfig mocks base method.
func (m *MockDedicatedInferenceService) GetGPUModelConfig(arg0 context.Context) (*godo.DedicatedInferenceGPUModelConfigResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGPUModelConfig", arg0)
	ret0, _ := ret[0].(*godo.DedicatedInferenceGPUModelConfigResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetGPUModelConfig indicates an expected call of GetGPUModelConfig.
func (mr *MockDedicatedInferenceServiceMockRecorder) GetGPUModelConfig(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGPUModelConfig", reflect.TypeOf((*MockDedicatedInferenceService)(nil).GetGPUModelConfig), arg0)
}

// GetSizes mocks base method.
func (m *MockDedicatedInferenceService) GetSizes(arg0 context.Context) (*godo.DedicatedInferenceSizesResponse, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSizes", arg0)
	ret0, _ := ret[0].(*godo.DedicatedInferenceSizesResponse)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSizes indicates an expected call of GetSizes.
func (mr *MockDedicatedInferenceServiceMockRecorder) GetSizes(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSizes", reflect.TypeOf((*MockDedicatedInferenceService)(nil).GetSizes), arg0)
}

// List mocks base method.
func (m *MockDedicatedInferenceService) List(arg0 context.Context, arg1 *godo.DedicatedInferenceListOptions) ([]godo.DedicatedInferenceListItem, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]godo.DedicatedInferenceListItem)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockDedicatedInferenceServiceMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDedicatedInferenceService)(nil).List), arg0, arg1)
}

// ListAccelerators mocks base method.
func (m *MockDedicatedInferenceService) ListAccelerators(arg0 context.Context, arg1 string, arg2 *godo.DedicatedInferenceListAcceleratorsOptions) ([]godo.DedicatedInferenceAcceleratorInfo, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccelerators", arg0, arg1, arg2)
	ret0, _ := ret[0].([]godo.DedicatedInferenceAcceleratorInfo)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAccelerators indicates an expected call of ListAccelerators.
func (mr *MockDedicatedInferenceServiceMockRecorder) ListAccelerators(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccelerators", reflect.TypeOf((*MockDedicatedInferenceService)(nil).ListAccelerators), arg0, arg1, arg2)
}

// ListTokens mocks base method.
func (m *MockDedicatedInferenceService) ListTokens(arg0 context.Context, arg1 string, arg2 *godo.ListOptions) ([]godo.DedicatedInferenceToken, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTokens", arg0, arg1, arg2)
	ret0, _ := ret[0].([]godo.DedicatedInferenceToken)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTokens indicates an expected call of ListTokens.
func (mr *MockDedicatedInferenceServiceMockRecorder) ListTokens(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTokens", reflect.TypeOf((*MockDedicatedInferenceService)(nil).ListTokens), arg0, arg1, arg2)
}

// RevokeToken mocks base method.
func (m *MockDedicatedInferenceService) RevokeToken(arg0 context.Context, arg1, arg2 string) (*godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeToken", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockDedicatedInferenceServiceMockRecorder) RevokeToken(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockDedicatedInferenceService)(nil).RevokeToken), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockDedicatedInferenceService) Update(arg0 context.Context, arg1 string, arg2 *godo.DedicatedInferenceUpdateRequest) (*godo.DedicatedInference, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.DedicatedInference)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Update indicates an expected call of Update.
func (mr *MockDedicatedInferenceServiceMockRecorder) Update(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDedicatedInferenceService)(nil).Update), arg0, arg1, arg2)
}
