// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/digitalocean/godo (interfaces: FunctionsService)
//
// Generated by this command:
//
//	mockgen -destination=./mocks.go -package serverless github.com/digitalocean/godo FunctionsService
//

// Package serverless is a generated GoMock package.
package serverless

import (
	context "context"
	reflect "reflect"

	godo "github.com/digitalocean/godo"
	gomock "go.uber.org/mock/gomock"
)

// MockFunctionsService is a mock of FunctionsService interface.
type MockFunctionsService struct {
	ctrl     *gomock.Controller
	recorder *MockFunctionsServiceMockRecorder
	isgomock struct{}
}

// MockFunctionsServiceMockRecorder is the mock recorder for MockFunctionsService.
type MockFunctionsServiceMockRecorder struct {
	mock *MockFunctionsService
}

// NewMockFunctionsService creates a new mock instance.
func NewMockFunctionsService(ctrl *gomock.Controller) *MockFunctionsService {
	mock := &MockFunctionsService{ctrl: ctrl}
	mock.recorder = &MockFunctionsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFunctionsService) EXPECT() *MockFunctionsServiceMockRecorder {
	return m.recorder
}

// CreateNamespace mocks base method.
func (m *MockFunctionsService) CreateNamespace(arg0 context.Context, arg1 *godo.FunctionsNamespaceCreateRequest) (*godo.FunctionsNamespace, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNamespace", arg0, arg1)
	ret0, _ := ret[0].(*godo.FunctionsNamespace)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateNamespace indicates an expected call of CreateNamespace.
func (mr *MockFunctionsServiceMockRecorder) CreateNamespace(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNamespace", reflect.TypeOf((*MockFunctionsService)(nil).CreateNamespace), arg0, arg1)
}

// CreateTrigger mocks base method.
func (m *MockFunctionsService) CreateTrigger(arg0 context.Context, arg1 string, arg2 *godo.FunctionsTriggerCreateRequest) (*godo.FunctionsTrigger, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTrigger", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.FunctionsTrigger)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateTrigger indicates an expected call of CreateTrigger.
func (mr *MockFunctionsServiceMockRecorder) CreateTrigger(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTrigger", reflect.TypeOf((*MockFunctionsService)(nil).CreateTrigger), arg0, arg1, arg2)
}

// DeleteNamespace mocks base method.
func (m *MockFunctionsService) DeleteNamespace(arg0 context.Context, arg1 string) (*godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNamespace", arg0, arg1)
	ret0, _ := ret[0].(*godo.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteNamespace indicates an expected call of DeleteNamespace.
func (mr *MockFunctionsServiceMockRecorder) DeleteNamespace(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNamespace", reflect.TypeOf((*MockFunctionsService)(nil).DeleteNamespace), arg0, arg1)
}

// DeleteTrigger mocks base method.
func (m *MockFunctionsService) DeleteTrigger(arg0 context.Context, arg1, arg2 string) (*godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTrigger", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTrigger indicates an expected call of DeleteTrigger.
func (mr *MockFunctionsServiceMockRecorder) DeleteTrigger(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTrigger", reflect.TypeOf((*MockFunctionsService)(nil).DeleteTrigger), arg0, arg1, arg2)
}

// GetNamespace mocks base method.
func (m *MockFunctionsService) GetNamespace(arg0 context.Context, arg1 string) (*godo.FunctionsNamespace, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespace", arg0, arg1)
	ret0, _ := ret[0].(*godo.FunctionsNamespace)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetNamespace indicates an expected call of GetNamespace.
func (mr *MockFunctionsServiceMockRecorder) GetNamespace(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespace", reflect.TypeOf((*MockFunctionsService)(nil).GetNamespace), arg0, arg1)
}

// GetTrigger mocks base method.
func (m *MockFunctionsService) GetTrigger(arg0 context.Context, arg1, arg2 string) (*godo.FunctionsTrigger, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrigger", arg0, arg1, arg2)
	ret0, _ := ret[0].(*godo.FunctionsTrigger)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTrigger indicates an expected call of GetTrigger.
func (mr *MockFunctionsServiceMockRecorder) GetTrigger(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrigger", reflect.TypeOf((*MockFunctionsService)(nil).GetTrigger), arg0, arg1, arg2)
}

// ListNamespaces mocks base method.
func (m *MockFunctionsService) ListNamespaces(arg0 context.Context) ([]godo.FunctionsNamespace, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNamespaces", arg0)
	ret0, _ := ret[0].([]godo.FunctionsNamespace)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListNamespaces indicates an expected call of ListNamespaces.
func (mr *MockFunctionsServiceMockRecorder) ListNamespaces(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNamespaces", reflect.TypeOf((*MockFunctionsService)(nil).ListNamespaces), arg0)
}

// ListTriggers mocks base method.
func (m *MockFunctionsService) ListTriggers(arg0 context.Context, arg1 string) ([]godo.FunctionsTrigger, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTriggers", arg0, arg1)
	ret0, _ := ret[0].([]godo.FunctionsTrigger)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTriggers indicates an expected call of ListTriggers.
func (mr *MockFunctionsServiceMockRecorder) ListTriggers(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTriggers", reflect.TypeOf((*MockFunctionsService)(nil).ListTriggers), arg0, arg1)
}

// UpdateTrigger mocks base method.
func (m *MockFunctionsService) UpdateTrigger(arg0 context.Context, arg1, arg2 string, arg3 *godo.FunctionsTriggerUpdateRequest) (*godo.FunctionsTrigger, *godo.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTrigger", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*godo.FunctionsTrigger)
	ret1, _ := ret[1].(*godo.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateTrigger indicates an expected call of UpdateTrigger.
func (mr *MockFunctionsServiceMockRecorder) UpdateTrigger(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTrigger", reflect.TypeOf((*MockFunctionsService)(nil).UpdateTrigger), arg0, arg1, arg2, arg3)
}
